services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: olympus_database
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=#Olympus@2025
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - database:/var/opt/mssql

  redis:
    image: redis:8
    container_name: olympus_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  database:
  cache:
