services:
  postgres:
    image: postgres:17
    container_name: olympus_database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=Olympus
      - POSTGRES_PASSWORD=#Olympus@2025
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
  cache:
