services:
  production-dashboard:
    image: "mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest"
    ports:
      - "18888"
    expose:
      - "18889"
      - "18890"
    networks:
      - "aspire"
    restart: "always"
  postgres:
    image: "docker.io/library/postgres:17"
    container_name: "postgres"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose:
      - "5432"
    volumes:
      - type: "volume"
        target: "/var/lib/postgresql/data"
        source: "postgres"
        read_only: false
    networks:
      - "aspire"
  minio:
    image: "docker.io/minio/minio:RELEASE.2025-09-07T16-13-09Z"
    container_name: "minio"
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USERNAME}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    expose:
      - "9000"
      - "9001"
    volumes:
      - type: "volume"
        target: "/data"
        source: "minio"
        read_only: false
    networks:
      - "aspire"
  redis:
    image: "docker.io/library/redis:8"
    container_name: "redis"
    command:
      - "-c"
      - "redis-server --requirepass $$REDIS_PASSWORD --save 60 1"
    entrypoint:
      - "/bin/sh"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    expose:
      - "6379"
    volumes:
      - type: "volume"
        target: "/data"
        source: "redis"
        read_only: false
    networks:
      - "aspire"
  api:
    image: "${API_IMAGE}"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "${API_PORT}"
      ConnectionStrings__Database: "Host=Postgres;Port=5432;Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD};Database=Database"
      DATABASE_HOST: "Postgres"
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: "${POSTGRES_USERNAME}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
      DATABASE_URI: "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@Postgres:5432/Database"
      DATABASE_JDBCCONNECTIONSTRING: "jdbc:postgresql://Postgres:5432/Database"
      DATABASE_DATABASENAME: "Database"
      ConnectionStrings__Minio: "Endpoint=http://Minio:9000;AccessKey=${MINIO_USERNAME};SecretKey=${MINIO_PASSWORD}"
      MINIO_HOST: "Minio"
      MINIO_PORT: "9000"
      MINIO_ACCESSKEY: "${MINIO_USERNAME}"
      MINIO_SECRETKEY: "${MINIO_PASSWORD}"
      MINIO_URI: "http://Minio:9000"
      ConnectionStrings__Redis: "Redis:6379,password=${REDIS_PASSWORD}"
      REDIS_HOST: "Redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_URI: "redis://:${REDIS_PASSWORD}@Redis:6379"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://Production-dashboard:18889"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "API"
    ports:
      - "${API_PORT}"
    depends_on:
      postgres:
        condition: "service_started"
      minio:
        condition: "service_started"
      redis:
        condition: "service_started"
    networks:
      - "aspire"
networks:
  aspire:
    driver: "bridge"
volumes:
  postgres:
    driver: "local"
  minio:
    driver: "local"
  redis:
    driver: "local"
