name: Badges

on:
  push:
    branches:
      - main
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_badges:
    runs-on: ubuntu-latest
    name: Create Badges
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Tags
        run: git fetch --tags --force

      - name: Get Repository Name
        run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Generate Badges
        uses: thewerthon/RepoBadges@v1.0.3
        with:
          directory: ./
          patterns: "**/*.bru|**/*.cs|**/*.cshtml|**/*.csproj|**/*.css|**/*.html|**/*.js|**/*.json|**/*.props|**/*.ps1|**/*.razor|**/*.sh|**/*.slnx|**/*.targets|**/*.xaml|**/*.xml|**/*.yaml|**/*.yml"
          ignore: ".git|$Generated|bin|obj|**/*.Designer.cs|**/*.map|**/*.min.css|**/*.min.js"

      - name: Deploy to Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: olympus-app/badges
          publish_branch: ${{ env.REPO_NAME }}
          publish_dir: ./output
          personal_token: ${{ secrets.PRIVATE_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
